name: Stephane Van den Bossche
favicon: null
layout_spectrum: 0.27362658036872745
typography_spectrum: 0.6067838550079614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.33680937462486327
  lightness: 0.8016705513000488
  saturation: 0.13532424555160105
  rhythmicContrast: 0.948947838973254
purpose: []
